#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
	echo "Error"
	exit 1;
fi
}

BASEDIR=`dirname $0`

if [ $# -lt 1 ]; then echo "Error No inputs provided" && exit 1; fi

. $BASEDIR/io.sh 1 0 1 "$@"

#make temporary directory
TEMP=`pwd`/`uuidgen`
mkdir $TEMP

#copy input into local directory
cp $INPUTS1 $TEMP/input.bam

#Script that invokes samtools
docker run -v $TEMP:/out comics/samtools samtools sort -o /out/sorted.bam /out/input.bam
checkExitCode

#copy output
cp $TEMP/sorted.bam $OUTPUTS1

#remove temporary directory
rm -fr $TEMP

checkExitCode
